Nidhinanban/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using Nidhinanban.Services;
using Nidhinanban.Models;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http.HttpResults;

namespace Nidhinanban.Controllers
{
    public class CustomerController : Controller
    {

        private readonly AddCustomerService _addCustomerService;
        private readonly HttpClient _httpClient;
        public CustomerController(AddCustomerService addCustomerService, IHttpClientFactory httpClientFactory)
        {
            _addCustomerService = addCustomerService;
            _httpClient = httpClientFactory.CreateClient();
            _httpClient.BaseAddress = new Uri("https://localhost:7065/");
        }

        [HttpGet]
        public async Task<IActionResult> AddCustomer(AddCustomerModel model)
        {
            string id = await _addCustomerService.GetCustomerID();
            model.CustomerId = id;
            ModelState.Clear();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddCustomerToDatabase(AddCustomerModel model)
        {
            if (model == null)
            {
                return BadRequest("Model cannot be null");
            }
            if (ModelState.IsValid)
            {
                string status = await _addCustomerService.AddCustomer(model.CustomerId!, model.CustomerName!, model.CustomerPhonenumber!, model.CustomerAddress!, model.CustomerProfileimage!, model.CustomerAadharimage!, model.CustomerPancardimage!, model.CustomerHouseimage!);
                if (status.ToLower() == "inserted")
                {
                    model.success = true;
                    return PartialView("_added", model);
                }
            }
            else if (!ModelState.IsValid)
            {
                model.success = false;
                foreach (var error in ModelState)
                {
                    Console.WriteLine($"Key: {error.Key}");
                    foreach (var e in error.Value.Errors)
                    {
                        Console.WriteLine($"Error: {e.ErrorMessage}");
                    }
                }
            }
            return PartialView("_added", model);
        }
        [HttpGet]
        public async Task<IActionResult> ViewCustomer()
        {
            var response = await _httpClient.GetAsync("/View/ViewCustomer/getall");
            if (!response.IsSuccessStatusCode) //check's the response code is success or not 
            {
                ViewBag.Error = "No customers found";
                return View(new List<ViewCustomer>());
            }
            var data = await response.Content.ReadFromJsonAsync<List<ViewCustomer>>();
            return View(data);
        }

        [HttpGet]
        public async Task<IActionResult> ViewCustomerlist()
        {
            var response = await _httpClient.GetAsync("/View/ViewCustomer/getall");
            if (!response.IsSuccessStatusCode) //check's the response code is success or not
            {
                ViewBag.Error = "No customers found";
                return View(new List<ViewCustomer>());
            }
            
            var data = await response.Content.ReadFromJsonAsync<List<ViewCustomer>>();
            return View(data);
        }
        [HttpGet]
        public async Task<IActionResult> CustomerDetails()
        {
            string id = Request.Query["id"]!;
            if (!Request.Query.TryGetValue("id", out var idValue) || string.IsNullOrEmpty(idValue))
            {
                return RedirectToAction("ViewCustomer");
            }
            var response = await _httpClient.GetAsync($"/View/ViewCustomer/{id}");
            var customerdetail = await response.Content.ReadFromJsonAsync<List<ViewCustomer>>();
            if (customerdetail!.Count == 0)
            {
                return BadRequest("Error");
            }
            return View(customerdetail);
        }
    }
}

Nidhinanban/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Nidhinanban.Models;

namespace Nidhinanban.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }
    
    public IActionResult ViewIntreset()
    {
        return View();
    }
    
    [HttpPost]
    public IActionResult ViewIntreset(ViewIntresetModel input)
    {
        if (input is null)
        {
            throw new ArgumentNullException(nameof(input));
        }

        Console.WriteLine("Input amount"+input.amount.ToString());
        decimal amount = input.amount;
        decimal month = input.month;
        decimal interestrate    = input.interestrate;
        input.totalamount = Math.Ceiling((amount*interestrate*month)/100);
        Console.WriteLine(""+input.totalamount);
            return View(input);
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Nidhinanban/Controllers/IntrestController.cs
using System.Security.Principal;
using System.Data;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Nidhinanban.Models;
using Nidhinanban.Services;
using Newtonsoft.Json;
using Nidhinanban.LogicClasses;

namespace Nidhinanban.Controllers
{



    public class IntrestController : Controller
    {
        private readonly InterestService _interestService;
        public IntrestController(){
            _interestService = new InterestService();
        }
        [HttpGet]
        public IActionResult Intrestcalc()
        {
            return View(new InterestModel());
        }

        [HttpPost]
        public async Task<IActionResult> Intrestcalc(InterestModel interestModel)
        {
            if(ModelState.IsValid)
            {
                LogicClasses.Intrest intrest=new LogicClasses.Intrest();
                float principleamount=interestModel.principleamount;
                float interestrate=interestModel.interestrate;
                float tenure=interestModel.tenure;
                string type=interestModel.type;
                if(principleamount!=0)
                {
                        interestModel.showdiv=true;
                }
                else{
                        interestModel.showdiv=false;
                }
                if(interestrate==0)
                {
                    interestrate=1;
                }
                var status= await _interestService.calculateinterest(principleamount,interestrate,tenure,type);
                interestModel.principleamountstring=status.principleamount;
                interestModel.intrestamount=status.interestamount;
                interestModel.totalamount=status.totalamount;
                interestModel.dt=await intrest.getWeekbasedInterestData(tenure,interestrate.ToString(),principleamount.ToString(),type);
                TempData["ScheduleData"] = JsonConvert.SerializeObject(interestModel.dt);
                TempData["IntrestAmount"]=JsonConvert.SerializeObject(status.interestamount);
                TempData["Principleamount"]=JsonConvert.SerializeObject(status.principleamount);
                TempData["TotalAmount"]=JsonConvert.SerializeObject(status.totalamount);
                
            }
            return PartialView("_Intresthidden",interestModel);
        }
        public IActionResult ExportExcel()
        {
            string? json=TempData["ScheduleData"]?.ToString();
            string? interestamount=TempData["IntrestAmount"]?.ToString();
            string? principleamount=TempData["Principleamount"]?.ToString();
            string? totalamount=TempData["TotalAmount"]?.ToString();
            string result=String.IsNullOrEmpty(json) ?"":json;
            var dataTable = JsonConvert.DeserializeObject<DataTable>(result);
            var fileBytes = Exporter.ExportInterestViewExcel(interestamount!,principleamount!,totalamount!,dataTable!);
            string filename="Interest Report "+DateTime.Now.ToString("");
            return File(fileBytes, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", filename);
        }
    }
}

Nidhinanban/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="text-center" data-tilt>Welcome To Nidhinanban</h1>
    <div class="container">
        <div class="row justify-content-center my-5">
            <div class="col-lg-3 col-md-4 col-sm-6 col-10 my-3 animate__animated animate__bounceInLeft" >
                <div class="card border border-10 shadow-sm h-100">
                    <img width="90" height="90" src="https://img.icons8.com/fluency/144/accounting.png" alt="accounting" class="mx-auto my-4"/>
                    <h4 class="my-3">Interest Calculator</h4>
                    <h6 class="text-secondary">Calculate The Interest</h6>
                    <a class="btn btn-outline-purple  w-75 mx-auto border my-4"  asp-controller="Intrest" asp-action="Intrestcalc">Open Calculator</a>
                    </div>
                </div>
            <div class="col-lg-3 col-md-4 col-sm-6 col-10 my-3 animate__animated  animate__bounceInDown" >
                <div class="card border border-10 shadow-sm h-100">
                    <img width="90" height="90" src="https://img.icons8.com/fluency/144/gender-neutral-user--v1.png" alt="gender-neutral-user--v1" class="mx-auto my-4"/>
                    <h4 class="my-3">Customer</h4>
                    <h6 class="text-secondary">Add & Manage Customer </h6>
                    <a class="btn bnt-gradient-primary w-75 mx-auto border my-4" asp-controller="Customer" asp-action="AddCustomer">Open Customer</a>
                </div>
            </div>
            <div class="col-lg-3 col-md-4 col-sm-6 col-10 my-3 animate__animated  animate__bounceInRight">
                <div class="card border border-10 shadow-sm h-100">
                    <img width="90" height="90" src="https://img.icons8.com/fluency/144/high-importance.png" alt="high-importance" class="mx-auto my-4"/>
                    <h4 class="my-3">Late Payment Fines</h4>
                    <h6 class="text-secondary text-center mx-auto">Calculate penalites for late payments</h6>
                    <button class="btn btn-outline-light text-black w-75 mx-auto border my-4">Open Calculator</button>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $('.js-tilt').tilt({
    scale:2.2
})
</script>

Nidhinanban/Views/Home/ViewIntreset.cshtml
@model  ViewIntresetModel
@{
    ViewData["Title"]="Intrest";
}

<div>
    <div class="container-fluid">
        <form asp-action="ViewIntreset" method="post">
        <div class=" text-center card  mx-auto  col-lg-5 col-md-6 col-sm-10  ">
        <div class="card-header">
            <h2 class="title"> View Interest</h2>
        </div>
        <div class="card-body">

                <div class="my-2">
                    <label class="my-2"> Principle Amount</label>

                    <input type="number" asp-for=amount class="form-control" name="amount" id="amount"
                        placeholder="Enter The Amount" />
                </div>
                 <div class="my-2">
                    <label class="my-2"> Intrest</label>

                    <input type="number" asp-for=interestrate class="form-control" name="intrest" id="intrest"
                        placeholder="Enter The Intrest Rate" />
                </div>
                 <div class="my-2">
                    <label class="my-2"> Number Of Years</label>

                    <input type="number" asp-asp-for=year class="form-control" name="year" id="year"
                        placeholder="Enter The Total Number of Years" />
                </div>
                 <div class="my-2">
                    <label class="my-2"> Months</label>

                    <input type="text" asp-for=month class="form-control" name="amount" id="amount"
                        placeholder="Enter The Total Number Of Months" />
                </div>

                <div class="my-2">
                    <label class="my-2"> Intrest Amount</label>

                    <input type="number" asp-for=interestamount class="form-control" name="intresetamount" id="intrestamount"
                        placeholder="" readonly />
                </div>

                <div class="my-2">
                    <label class="my-2"> Total Amount</label>

                    <input type="number" asp-for=totalamount class="form-control" name="totalamount" id="totalamount"
                        placeholder="" readonly />
                </div>
                <div class="my-2">
                   <button class="btn btn-success" id="calculate" value="Calculate" width="200"> Calculate</button>
                </div>
            </div>
            
        </div>
        </form>
        <div class="col-lg-3 my-5">
            <table>
                <thead>Demo</thead>
                <tr>
                    <td>Hello World</td>
                </tr>
                <tr>
                    <td>Hello WOrld1</td>
                </tr>
            </table>
        </div>
    </div>
    
    </div>
    
</div>